
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyAspx.EasyFramework.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class my_fileinfo
{

    public int fileid { get; set; }

    public Nullable<int> fileclassid { get; set; }

    public string filevstype { get; set; }

    public string filedevlan { get; set; }

    public Nullable<int> downid { get; set; }

    public string fileremark { get; set; }

    public Nullable<int> filedownnum { get; set; }

    public string filepics { get; set; }

}

}
