
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyAspx.EasyFramework.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class my_fileinfo
{

    public int fileid { get; set; }

    public int fileclassid { get; set; }

    public string filevstype { get; set; }

    public string filedevlan { get; set; }

    public int downid { get; set; }

    public string fileremark { get; set; }

    public Nullable<int> filedownnum { get; set; }

    public string filepics { get; set; }

    public string filename { get; set; }

    public int goldid { get; set; }

    public string codeplftype { get; set; }

    public string devtool { get; set; }

    public string filedatabase { get; set; }

    public string frameworkversion { get; set; }

    public int tagid { get; set; }

    public string linkurl { get; set; }

    public string createuser { get; set; }

    public string contract { get; set; }

    public string usermsg { get; set; }

    public string codedes { get; set; }

}

}
