//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAspx.EasyFramework.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_fileinfo
    {
        public string fileid { get; set; }
        public Nullable<int> saletypeid { get; set; }
        public Nullable<int> fileclassid { get; set; }
        public string filevstype { get; set; }
        public string filedevlan { get; set; }
        public Nullable<int> downid { get; set; }
        public Nullable<int> filedownnum { get; set; }
        public string filepics { get; set; }
        public string filename { get; set; }
        public string codeplftype { get; set; }
        public string devtool { get; set; }
        public string filedatabase { get; set; }
        public string frameworkversion { get; set; }
        public Nullable<int> tagid { get; set; }
        public string linkurl { get; set; }
        public string createuser { get; set; }
        public string contract { get; set; }
        public string usermsg { get; set; }
        public string codedes { get; set; }
        public string codelang { get; set; }
        public string filefirimg { get; set; }
    }
}
