//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAspx.EasyFramework.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_gold
    {
        public int goldid { get; set; }
        public Nullable<decimal> goldnum { get; set; }
        public Nullable<int> golduserid { get; set; }
        public Nullable<int> goldpaynum { get; set; }
    }
}
