//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAspx.EasyFramework.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_message
    {
        public int mesid { get; set; }
        public string mescontext { get; set; }
        public Nullable<int> meshasguest { get; set; }
        public string meswriter { get; set; }
        public string mesdate { get; set; }
        public Nullable<int> mespid { get; set; }
    }
}
