//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAspx.EasyFramework.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_pay
    {
        public int payid { get; set; }
        public string paydate { get; set; }
        public Nullable<decimal> paynum { get; set; }
        public int payuseid { get; set; }
        public string payform { get; set; }
    }
}
