
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyAspx.EasyFramework.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class my_siteconf
{

    public int siteid { get; set; }

    public string sitetitle { get; set; }

    public string sitekeywords { get; set; }

    public string sitedescription { get; set; }

    public string sitewriter { get; set; }

    public string siteremark { get; set; }

    public Nullable<System.DateTime> siteaddtime { get; set; }

}

}
