//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAspx.EasyFramework.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_users
    {
        public int userid { get; set; }
        public string useregname { get; set; }
        public string userpwd { get; set; }
        public string userregip { get; set; }
        public string usercreatedate { get; set; }
        public string useraddress { get; set; }
        public int usersex { get; set; }
        public string userremark { get; set; }
        public string uselogopic { get; set; }
    }
}
